spring:
  application:
    name: library-links
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  # db migrations
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

elastic:
  host: localhost
  port: 9200