version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
